# Generated by Django 3.0.8 on 2020-07-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200706_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberslist',
            name='ok',
            field=models.BooleanField(default=False),
        ),
    ]
